networks:
  socket-network:
    driver: bridge

volumes:
  mysql-volume:
  prom-volume:
  grafana-volume:

services:
  mysql:
    image: mysql:8.0
    container_name: socket-mysql
    restart: unless-stopped
    ports:
      - "3003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Spring_Chatting
      MYSQL_USER: chatting
      MYSQL_PASSWORD: chatting
      TZ: "Asia/Seoul"
    command:
      - --default-time-zone=+09:00
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      - --max_allowed_packet=256M
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - socket-network