server:
  port: 7002

springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method

spring:
  application:
    name: socket

  datasource:
    url: jdbc:mysql://localhost:3003/Spring_Chatting
    username: chatting
    password: chatting
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

token:
  secret-key: "this-is-a-very-long-secret-key-for-access-token-123456"
  refresh-secret-key: "this-is-a-very-long-secret-key-for-refresh-token-abcdef"
  token-time: 60
  refresh-token-time: 1440